// Curated option lists for the company form's searchable dropdowns.
// City/Industry stay "allowCustom" since these lists are shortlists, not
// exhaustive — State stays a strict list since India's states are fixed.

export const INDUSTRIES = [
  "Information Technology",
  "Software / SaaS",
  "E-commerce",
  "Retail",
  "Manufacturing",
  "Real Estate",
  "Construction",
  "Healthcare",
  "Pharmaceuticals",
  "Education",
  "Finance / Banking",
  "Insurance",
  "Hospitality",
  "Travel & Tourism",
  "Media & Entertainment",
  "Advertising & Marketing",
  "Logistics & Supply Chain",
  "Automotive",
  "Agriculture",
  "Telecommunications",
  "Legal Services",
  "Consulting",
  "Non-Profit / NGO",
  "Food & Beverage",
  "Fashion & Apparel",
  "Energy & Utilities",
  "Other",
];

export const LEAD_SOURCES = [
  "Google",
  "Email Marketing",
  "Instagram",
  "WhatsApp",
  "Facebook",
  "LinkedIn",
  "Referral",
  "Website",
  "Cold Outreach",
  "Event / Conference",
  "Other",
];

export const INDIAN_STATES = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const INDIAN_CITIES = [
  "Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata",
  "Surat", "Pune", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane",
  "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad", "Patna", "Vadodara", "Ghaziabad",
  "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli",
  "Vasai-Virar", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar",
  "Navi Mumbai", "Allahabad", "Ranchi", "Howrah", "Coimbatore", "Jabalpur",
  "Gwalior", "Vijayawada", "Jodhpur", "Madurai", "Raipur", "Kota", "Guwahati",
  "Chandigarh", "Thiruvananthapuram", "Solapur", "Hubli-Dharwad", "Mysore",
  "Tiruchirappalli", "Bareilly", "Aligarh", "Tiruppur", "Gurgaon", "Moradabad",
  "Jalandhar", "Bhubaneswar", "Salem", "Noida", "Bhiwandi", "Amravati",
  "Cuttack", "Firozabad", "Kochi", "Nellore", "Bhavnagar", "Dehradun",
  "Durgapur", "Asansol", "Rourkela", "Nanded", "Kolhapur", "Ajmer", "Akola",
  "Gulbarga", "Jamnagar", "Ujjain", "Loni", "Siliguri", "Jhansi", "Ulhasnagar",
  "Jammu", "Mangalore", "Erode", "Belgaum", "Tirunelveli", "Malegaon",
  "Gaya", "Jalgaon", "Udaipur", "Maheshtala",
];
