/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["DM Sans", "system-ui", "sans-serif"],
        display: ["DM Sans", "system-ui", "sans-serif"],
        inter: ["DM Sans", "system-ui", "sans-serif"],
      },
      colors: {
        primary: { DEFAULT: "#8D3118", dark: "#8D3118", light: "#FFFFFF", container: "#8D3118", fixed: "#E5E7EB" },
        studio: {
          background: "#F1F1F5",
          surface: "#FFFFFF",
          card: "#E5E7EB",
          border: "#6B7280",
          muted: "#6B7280",
          copper: "#8D3118",
        },
        /* Copper Studio OS tokens (for client portal) */
        "cs-primary": "#8D3118",
        "cs-primary-container": "#8D3118",
        "cs-primary-fixed": "#E5E7EB",
        "cs-on-primary": "#ffffff",
        "cs-background": "#FFFFFF",
        "cs-surface": "#FFFFFF",
        "cs-surface-lowest": "#ffffff",
        "cs-surface-low": "#FFFFFF",
        "cs-surface-container": "#FFFFFF",
        "cs-surface-high": "#E5E7EB",
        "cs-surface-highest": "#E5E7EB",
        "cs-outline-variant": "#6B7280",
        "cs-on-surface": "#1A1A1A",
        "cs-on-surface-variant": "#1A1A1A",
        "cs-secondary": "#6B7280",
        "cs-error": "#8D3118",
        /* Material Design color tokens used in UI HTML */
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#FFFFFF",
        "surface-container": "#FFFFFF",
        "surface-container-high": "#E5E7EB",
        "surface-container-highest": "#E5E7EB",
        "primary-container": "#8D3118",
        "primary-fixed": "#E5E7EB",
        "primary-fixed-dim": "#8D3118",
        "outline-variant": "#6B7280",
        "on-surface": "#1A1A1A",
        "on-surface-variant": "#1A1A1A",
        "secondary-container": "#E5E7EB",
        "surface-bright": "#FFFFFF",
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
        elevated: "0 4px 16px rgba(0,0,0,0.08)",
      },
    },
  },
  plugins: [],
};
